// Code generated by Scalar SDK Generator. DO NOT EDIT.
#include <demo_api_scalar_galaxy_cpp/client.hpp>

namespace demo_api_scalar_galaxy {

AuthenticationResource::AuthenticationResource(ApiClient &client) : client_(client) {}

Response<User> AuthenticationResource::create_user(const AuthenticationResource::CreateUserParams &params,
                                                   const RequestOptions &request_options) const {
  Request request;
  request.method = "POST";
  request.path_template = "/user/signup";
  request.content_type = params.content_type;
  {
    json::Object body;
    if (params.name.has_value())
      body.emplace_back("name", json::encode(*params.name));
    body.emplace_back("email", json::encode(params.email));
    body.emplace_back("password", json::encode(params.password));
    request.body = json::dump(json::Value(std::move(body)));
  }
  return client_.send<User>(request, request_options);
}

Response<RawResponse> AuthenticationResource::create_user_raw(const AuthenticationResource::CreateUserParams &params,
                                                              const RequestOptions &request_options) const {
  Request request;
  request.method = "POST";
  request.path_template = "/user/signup";
  request.content_type = params.content_type;
  {
    json::Object body;
    if (params.name.has_value())
      body.emplace_back("name", json::encode(*params.name));
    body.emplace_back("email", json::encode(params.email));
    body.emplace_back("password", json::encode(params.password));
    request.body = json::dump(json::Value(std::move(body)));
  }
  RawResponse raw = client_.send_raw(request, request_options);
  return Response<RawResponse>{raw.status_code, raw.headers, raw.body, raw};
}

Response<Token> AuthenticationResource::create_token(const AuthenticationResource::CreateTokenParams &params,
                                                     const RequestOptions &request_options) const {
  Request request;
  request.method = "POST";
  request.path_template = "/auth/token";
  request.content_type = params.content_type;
  {
    json::Object body;
    body.emplace_back("email", json::encode(params.email));
    body.emplace_back("password", json::encode(params.password));
    request.body = json::dump(json::Value(std::move(body)));
  }
  return client_.send<Token>(request, request_options);
}

Response<RawResponse> AuthenticationResource::create_token_raw(const AuthenticationResource::CreateTokenParams &params,
                                                               const RequestOptions &request_options) const {
  Request request;
  request.method = "POST";
  request.path_template = "/auth/token";
  request.content_type = params.content_type;
  {
    json::Object body;
    body.emplace_back("email", json::encode(params.email));
    body.emplace_back("password", json::encode(params.password));
    request.body = json::dump(json::Value(std::move(body)));
  }
  RawResponse raw = client_.send_raw(request, request_options);
  return Response<RawResponse>{raw.status_code, raw.headers, raw.body, raw};
}

Response<User> AuthenticationResource::list_me(const RequestOptions &request_options) const {
  Request request;
  request.method = "GET";
  request.path_template = "/me";
  return client_.send<User>(request, request_options);
}

Response<RawResponse> AuthenticationResource::list_me_raw(const RequestOptions &request_options) const {
  Request request;
  request.method = "GET";
  request.path_template = "/me";
  RawResponse raw = client_.send_raw(request, request_options);
  return Response<RawResponse>{raw.status_code, raw.headers, raw.body, raw};
}

} // namespace demo_api_scalar_galaxy
