// Code generated by Scalar SDK Generator. DO NOT EDIT.
#include <demo_api_scalar_galaxy_cpp/client.hpp>

namespace demo_api_scalar_galaxy {

CelestialBodiesResource::CelestialBodiesResource(ApiClient &client) : client_(client) {}

Response<CelestialBody> CelestialBodiesResource::create(const CelestialBodiesResource::CreateParams &params,
                                                        const RequestOptions &request_options) const {
  Request request;
  request.method = "POST";
  request.path_template = "/celestial-bodies";
  request.content_type = "application/json";
  request.body = to_request_body(params.body);
  return client_.send<CelestialBody>(request, request_options);
}

Response<RawResponse> CelestialBodiesResource::create_raw(const CelestialBodiesResource::CreateParams &params,
                                                          const RequestOptions &request_options) const {
  Request request;
  request.method = "POST";
  request.path_template = "/celestial-bodies";
  request.content_type = "application/json";
  request.body = to_request_body(params.body);
  RawResponse raw = client_.send_raw(request, request_options);
  return Response<RawResponse>{raw.status_code, raw.headers, raw.body, raw};
}

} // namespace demo_api_scalar_galaxy
