// Code generated by Scalar SDK Generator. DO NOT EDIT.
#include <demo_api_scalar_galaxy_cpp/client.hpp>

namespace demo_api_scalar_galaxy {

PlanetsResource::PlanetsResource(ApiClient &client) : client_(client) {}

Response<std::map<std::string, std::string>> PlanetsResource::list(const PlanetsResource::ListParams &params,
                                                                   const RequestOptions &request_options) const {
  Request request;
  request.method = "GET";
  request.path_template = "/planets";
  if (auto value = to_optional_request_value(params.limit))
    request.query.emplace("limit", *value);
  if (auto value = to_optional_request_value(params.offset))
    request.query.emplace("offset", *value);
  return client_.send<std::map<std::string, std::string>>(request, request_options);
}

Response<RawResponse> PlanetsResource::list_raw(const PlanetsResource::ListParams &params,
                                                const RequestOptions &request_options) const {
  Request request;
  request.method = "GET";
  request.path_template = "/planets";
  if (auto value = to_optional_request_value(params.limit))
    request.query.emplace("limit", *value);
  if (auto value = to_optional_request_value(params.offset))
    request.query.emplace("offset", *value);
  RawResponse raw = client_.send_raw(request, request_options);
  return Response<RawResponse>{raw.status_code, raw.headers, raw.body, raw};
}

Response<Planet> PlanetsResource::create(const PlanetsResource::CreateParams &params,
                                         const RequestOptions &request_options) const {
  Request request;
  request.method = "POST";
  request.path_template = "/planets";
  request.content_type = params.content_type;
  {
    json::Object body;
    body.emplace_back("name", json::encode(params.name));
    if (params.description.has_value())
      body.emplace_back("description", json::encode(*params.description));
    body.emplace_back("type", json::encode(params.type));
    if (params.habitability_index.has_value())
      body.emplace_back("habitabilityIndex", json::encode(*params.habitability_index));
    if (params.physical_properties.has_value())
      body.emplace_back("physicalProperties", json::encode(*params.physical_properties));
    if (params.atmosphere.has_value())
      body.emplace_back("atmosphere", json::encode(*params.atmosphere));
    if (params.discovered_at.has_value())
      body.emplace_back("discoveredAt", json::encode(*params.discovered_at));
    if (params.image.has_value())
      body.emplace_back("image", json::encode(*params.image));
    if (params.satellites.has_value())
      body.emplace_back("satellites", json::encode(*params.satellites));
    if (params.creator.has_value())
      body.emplace_back("creator", json::encode(*params.creator));
    if (params.tags.has_value())
      body.emplace_back("tags", json::encode(*params.tags));
    if (params.success_callback_url.has_value())
      body.emplace_back("successCallbackUrl", json::encode(*params.success_callback_url));
    if (params.failure_callback_url.has_value())
      body.emplace_back("failureCallbackUrl", json::encode(*params.failure_callback_url));
    request.body = json::dump(json::Value(std::move(body)));
  }
  return client_.send<Planet>(request, request_options);
}

Response<RawResponse> PlanetsResource::create_raw(const PlanetsResource::CreateParams &params,
                                                  const RequestOptions &request_options) const {
  Request request;
  request.method = "POST";
  request.path_template = "/planets";
  request.content_type = params.content_type;
  {
    json::Object body;
    body.emplace_back("name", json::encode(params.name));
    if (params.description.has_value())
      body.emplace_back("description", json::encode(*params.description));
    body.emplace_back("type", json::encode(params.type));
    if (params.habitability_index.has_value())
      body.emplace_back("habitabilityIndex", json::encode(*params.habitability_index));
    if (params.physical_properties.has_value())
      body.emplace_back("physicalProperties", json::encode(*params.physical_properties));
    if (params.atmosphere.has_value())
      body.emplace_back("atmosphere", json::encode(*params.atmosphere));
    if (params.discovered_at.has_value())
      body.emplace_back("discoveredAt", json::encode(*params.discovered_at));
    if (params.image.has_value())
      body.emplace_back("image", json::encode(*params.image));
    if (params.satellites.has_value())
      body.emplace_back("satellites", json::encode(*params.satellites));
    if (params.creator.has_value())
      body.emplace_back("creator", json::encode(*params.creator));
    if (params.tags.has_value())
      body.emplace_back("tags", json::encode(*params.tags));
    if (params.success_callback_url.has_value())
      body.emplace_back("successCallbackUrl", json::encode(*params.success_callback_url));
    if (params.failure_callback_url.has_value())
      body.emplace_back("failureCallbackUrl", json::encode(*params.failure_callback_url));
    request.body = json::dump(json::Value(std::move(body)));
  }
  RawResponse raw = client_.send_raw(request, request_options);
  return Response<RawResponse>{raw.status_code, raw.headers, raw.body, raw};
}

Response<Planet> PlanetsResource::retrieve(const PlanetsResource::RetrieveParams &params,
                                           const RequestOptions &request_options) const {
  Request request;
  request.method = "GET";
  request.path_template = "/planets/{planetId}";
  request.path_params.emplace("planetId", to_request_value(params.planet_id));
  return client_.send<Planet>(request, request_options);
}

Response<RawResponse> PlanetsResource::retrieve_raw(const PlanetsResource::RetrieveParams &params,
                                                    const RequestOptions &request_options) const {
  Request request;
  request.method = "GET";
  request.path_template = "/planets/{planetId}";
  request.path_params.emplace("planetId", to_request_value(params.planet_id));
  RawResponse raw = client_.send_raw(request, request_options);
  return Response<RawResponse>{raw.status_code, raw.headers, raw.body, raw};
}

Response<Planet> PlanetsResource::update(const PlanetsResource::UpdateParams &params,
                                         const RequestOptions &request_options) const {
  Request request;
  request.method = "PUT";
  request.path_template = "/planets/{planetId}";
  request.content_type = params.content_type;
  request.path_params.emplace("planetId", to_request_value(params.planet_id));
  {
    json::Object body;
    body.emplace_back("name", json::encode(params.name));
    if (params.description.has_value())
      body.emplace_back("description", json::encode(*params.description));
    body.emplace_back("type", json::encode(params.type));
    if (params.habitability_index.has_value())
      body.emplace_back("habitabilityIndex", json::encode(*params.habitability_index));
    if (params.physical_properties.has_value())
      body.emplace_back("physicalProperties", json::encode(*params.physical_properties));
    if (params.atmosphere.has_value())
      body.emplace_back("atmosphere", json::encode(*params.atmosphere));
    if (params.discovered_at.has_value())
      body.emplace_back("discoveredAt", json::encode(*params.discovered_at));
    if (params.image.has_value())
      body.emplace_back("image", json::encode(*params.image));
    if (params.satellites.has_value())
      body.emplace_back("satellites", json::encode(*params.satellites));
    if (params.creator.has_value())
      body.emplace_back("creator", json::encode(*params.creator));
    if (params.tags.has_value())
      body.emplace_back("tags", json::encode(*params.tags));
    if (params.success_callback_url.has_value())
      body.emplace_back("successCallbackUrl", json::encode(*params.success_callback_url));
    if (params.failure_callback_url.has_value())
      body.emplace_back("failureCallbackUrl", json::encode(*params.failure_callback_url));
    request.body = json::dump(json::Value(std::move(body)));
  }
  return client_.send<Planet>(request, request_options);
}

Response<RawResponse> PlanetsResource::update_raw(const PlanetsResource::UpdateParams &params,
                                                  const RequestOptions &request_options) const {
  Request request;
  request.method = "PUT";
  request.path_template = "/planets/{planetId}";
  request.content_type = params.content_type;
  request.path_params.emplace("planetId", to_request_value(params.planet_id));
  {
    json::Object body;
    body.emplace_back("name", json::encode(params.name));
    if (params.description.has_value())
      body.emplace_back("description", json::encode(*params.description));
    body.emplace_back("type", json::encode(params.type));
    if (params.habitability_index.has_value())
      body.emplace_back("habitabilityIndex", json::encode(*params.habitability_index));
    if (params.physical_properties.has_value())
      body.emplace_back("physicalProperties", json::encode(*params.physical_properties));
    if (params.atmosphere.has_value())
      body.emplace_back("atmosphere", json::encode(*params.atmosphere));
    if (params.discovered_at.has_value())
      body.emplace_back("discoveredAt", json::encode(*params.discovered_at));
    if (params.image.has_value())
      body.emplace_back("image", json::encode(*params.image));
    if (params.satellites.has_value())
      body.emplace_back("satellites", json::encode(*params.satellites));
    if (params.creator.has_value())
      body.emplace_back("creator", json::encode(*params.creator));
    if (params.tags.has_value())
      body.emplace_back("tags", json::encode(*params.tags));
    if (params.success_callback_url.has_value())
      body.emplace_back("successCallbackUrl", json::encode(*params.success_callback_url));
    if (params.failure_callback_url.has_value())
      body.emplace_back("failureCallbackUrl", json::encode(*params.failure_callback_url));
    request.body = json::dump(json::Value(std::move(body)));
  }
  RawResponse raw = client_.send_raw(request, request_options);
  return Response<RawResponse>{raw.status_code, raw.headers, raw.body, raw};
}

Response<std::string> PlanetsResource::delete_(const PlanetsResource::DeleteParams &params,
                                               const RequestOptions &request_options) const {
  Request request;
  request.method = "DELETE";
  request.path_template = "/planets/{planetId}";
  request.path_params.emplace("planetId", to_request_value(params.planet_id));
  return client_.send<std::string>(request, request_options);
}

Response<RawResponse> PlanetsResource::delete__raw(const PlanetsResource::DeleteParams &params,
                                                   const RequestOptions &request_options) const {
  Request request;
  request.method = "DELETE";
  request.path_template = "/planets/{planetId}";
  request.path_params.emplace("planetId", to_request_value(params.planet_id));
  RawResponse raw = client_.send_raw(request, request_options);
  return Response<RawResponse>{raw.status_code, raw.headers, raw.body, raw};
}

Response<std::map<std::string, std::string>>
PlanetsResource::upload_image(const PlanetsResource::UploadImageParams &params,
                              const RequestOptions &request_options) const {
  Request request;
  request.method = "POST";
  request.path_template = "/planets/{planetId}/image";
  request.content_type = "multipart/form-data";
  request.path_params.emplace("planetId", to_request_value(params.planet_id));
  {
    json::Object body;
    if (params.image.has_value())
      body.emplace_back("image", json::encode(*params.image));
    request.body = json::dump(json::Value(std::move(body)));
  }
  return client_.send<std::map<std::string, std::string>>(request, request_options);
}

Response<RawResponse> PlanetsResource::upload_image_raw(const PlanetsResource::UploadImageParams &params,
                                                        const RequestOptions &request_options) const {
  Request request;
  request.method = "POST";
  request.path_template = "/planets/{planetId}/image";
  request.content_type = "multipart/form-data";
  request.path_params.emplace("planetId", to_request_value(params.planet_id));
  {
    json::Object body;
    if (params.image.has_value())
      body.emplace_back("image", json::encode(*params.image));
    request.body = json::dump(json::Value(std::move(body)));
  }
  RawResponse raw = client_.send_raw(request, request_options);
  return Response<RawResponse>{raw.status_code, raw.headers, raw.body, raw};
}

} // namespace demo_api_scalar_galaxy
