// Code generated by Scalar SDK Generator. DO NOT EDIT.
#include <demo_api_scalar_galaxy_cpp/client.hpp>

int main() {
  demo_api_scalar_galaxy::DemoApiScalarGalaxyClient client;
  (void)client;
  return 0;
}
