// Code generated by Scalar SDK Generator. DO NOT EDIT.
#pragma once

#include <demo_api_scalar_galaxy_cpp/models.hpp>
#include <demo_api_scalar_galaxy_cpp/request.hpp>
#include <demo_api_scalar_galaxy_cpp/webhooks.hpp>

#include <demo_api_scalar_galaxy_cpp/resources/authentication.hpp>
#include <demo_api_scalar_galaxy_cpp/resources/celestial_bodies.hpp>
#include <demo_api_scalar_galaxy_cpp/resources/planets.hpp>

#include <memory>
#include <optional>
#include <string>
#include <utility>

namespace demo_api_scalar_galaxy {

struct ClientOptions {
  std::string base_url = "https://galaxy.scalar.com";
  std::shared_ptr<Transport> transport;
  std::map<std::string, std::string> default_headers;
  std::map<std::string, std::string> default_query;
  int max_retries = 2;
  std::optional<std::string> bearer_auth_token;            // Defaults to "BEARER_AUTH_TOKEN" when unset.
  std::optional<std::string> basic_auth_credentials;       // Defaults to "BASIC_AUTH_TOKEN" when unset.
  std::optional<std::string> x_api_key;                    // Defaults to "API_KEY_HEADER_X_API_KEY" when unset.
  std::optional<std::string> api_key;                      // Defaults to "API_KEY_QUERY_API_KEY" when unset.
  std::optional<std::string> api_key;                      // Defaults to "API_KEY_COOKIE_API_KEY" when unset.
  std::optional<std::string> o_auth2_access_token;         // Defaults to "O_AUTH2_TOKEN" when unset.
  std::optional<std::string> open_id_connect_access_token; // Defaults to "OPEN_ID_CONNECT_TOKEN" when unset.
};

class ApiClient {
public:
  explicit ApiClient(ClientOptions options = {});

  [[nodiscard]] const ClientOptions &options() const noexcept { return options_; }

  template <typename T> Response<T> send(Request request, const RequestOptions &request_options = {}) const {
    apply_auth(request);
    RawResponse raw = send_raw(request, request_options);
    T data{};
    // Decode the JSON body into the typed model via the generated from_json (ADL). A parse
    // failure leaves a default-constructed value; raw_body always preserves the bytes.
    if (!raw.body.empty()) {
      if (const auto parsed = json::parse(raw.body))
        json::decode(*parsed, data);
    }
    return Response<T>{raw.status_code, raw.headers, raw.body, std::move(data)};
  }

  RawResponse send_raw(Request request, const RequestOptions &request_options = {}) const;

private:
  void apply_auth(Request &request) const;
  ClientOptions options_;
  std::optional<std::string> bearer_auth_token_;
  std::optional<std::string> basic_auth_credentials_;
  std::optional<std::string> x_api_key_;
  std::optional<std::string> api_key_;
  std::optional<std::string> api_key_;
  std::optional<std::string> o_auth2_access_token_;
  std::optional<std::string> open_id_connect_access_token_;
};

class DemoApiScalarGalaxyClient {
public:
  explicit DemoApiScalarGalaxyClient(ClientOptions options = {});

  [[nodiscard]] const ApiClient &api_client() const noexcept { return api_; }

  PlanetsResource planets;
  CelestialBodiesResource celestial_bodies;
  AuthenticationResource authentication;

private:
  ApiClient api_;
};

} // namespace demo_api_scalar_galaxy
