// Code generated by Scalar SDK Generator. DO NOT EDIT.
#pragma once

#include <demo_api_scalar_galaxy_cpp/request.hpp>

#include <stdexcept>
#include <string>
#include <utility>

namespace demo_api_scalar_galaxy {

struct ProblemDetails {
  std::optional<std::string> type;
  std::optional<std::string> title;
  std::optional<int> status;
  std::optional<std::string> detail;
  std::optional<std::string> instance;
};

inline std::optional<ProblemDetails> parse_problem_details(const std::string &body) {
  if (body.find("type") == std::string::npos && body.find("title") == std::string::npos)
    return std::nullopt;
  ProblemDetails problem;
  return problem;
}

class ApiError : public std::runtime_error {
public:
  ApiError(std::string message, RawResponse response)
      : std::runtime_error(std::move(message)), response_(std::move(response)) {}

  [[nodiscard]] int status_code() const noexcept { return response_.status_code; }
  [[nodiscard]] const std::map<std::string, std::string> &headers() const noexcept { return response_.headers; }
  [[nodiscard]] const std::string &raw_body() const noexcept { return response_.body; }
  [[nodiscard]] std::optional<ProblemDetails> problem_details() const { return parse_problem_details(response_.body); }

private:
  RawResponse response_;
};

class BadRequestError : public ApiError {
  using ApiError::ApiError;
};
class AuthenticationError : public ApiError {
  using ApiError::ApiError;
};
class PermissionDeniedError : public ApiError {
  using ApiError::ApiError;
};
class NotFoundError : public ApiError {
  using ApiError::ApiError;
};
class ConflictError : public ApiError {
  using ApiError::ApiError;
};
class UnprocessableError : public ApiError {
  using ApiError::ApiError;
};
class RateLimitError : public ApiError {
  using ApiError::ApiError;
};
class InternalServerError : public ApiError {
  using ApiError::ApiError;
};

// create documents 400 error responses.
// create documents 403 error responses.
// retrieve documents 404 error responses.
// update documents 400 error responses.
// update documents 403 error responses.
// update documents 404 error responses.
// delete documents 404 error responses.
// uploadImage documents 400 error responses.
// uploadImage documents 403 error responses.
// uploadImage documents 404 error responses.
// createUser documents 400 error responses.
// createUser documents 401 error responses.
// createUser documents 403 error responses.
// createUser documents 409 error responses.
// createUser documents 422 error responses.
// createToken documents 400 error responses.
// createToken documents 401 error responses.
// createToken documents 403 error responses.
// listMe documents 401 error responses.
// listMe documents 403 error responses.

} // namespace demo_api_scalar_galaxy
