// Code generated by Scalar SDK Generator. DO NOT EDIT.
#pragma once

#include <cstdint>
#include <cstdio>
#include <map>
#include <optional>
#include <string>
#include <string_view>
#include <type_traits>
#include <utility>
#include <variant>
#include <vector>

namespace demo_api_scalar_galaxy::json {

class Value;
// Object preserves insertion order and (unlike std::map) is guaranteed to support the
// recursive incomplete Value type, so the JSON DOM stays standard and dependency-free.
using Array = std::vector<Value>;
using Object = std::vector<std::pair<std::string, Value>>;

class Value {
public:
  using Storage = std::variant<std::nullptr_t, bool, std::int64_t, double, std::string, Array, Object>;

  Value() : data_(nullptr) {}
  Value(std::nullptr_t) : data_(nullptr) {}
  Value(bool value) : data_(value) {}
  Value(std::int64_t value) : data_(value) {}
  Value(double value) : data_(value) {}
  Value(std::string value) : data_(std::move(value)) {}
  Value(Array value) : data_(std::move(value)) {}
  Value(Object value) : data_(std::move(value)) {}

  [[nodiscard]] const Storage &data() const { return data_; }
  [[nodiscard]] bool is_null() const { return std::holds_alternative<std::nullptr_t>(data_); }
  [[nodiscard]] const Array *as_array() const { return std::get_if<Array>(&data_); }
  [[nodiscard]] const Object *as_object() const { return std::get_if<Object>(&data_); }
  [[nodiscard]] bool as_bool() const { return std::holds_alternative<bool>(data_) && std::get<bool>(data_); }
  [[nodiscard]] std::string as_string() const {
    if (const auto *value = std::get_if<std::string>(&data_))
      return *value;
    return {};
  }
  [[nodiscard]] std::int64_t as_int() const {
    if (const auto *value = std::get_if<std::int64_t>(&data_))
      return *value;
    if (const auto *value = std::get_if<double>(&data_))
      return static_cast<std::int64_t>(*value);
    return 0;
  }
  [[nodiscard]] double as_double() const {
    if (const auto *value = std::get_if<double>(&data_))
      return *value;
    if (const auto *value = std::get_if<std::int64_t>(&data_))
      return static_cast<double>(*value);
    return 0.0;
  }
  // Linear lookup keeps Object order-preserving; generated objects are small.
  [[nodiscard]] const Value *find(std::string_view key) const {
    if (const Object *object = as_object()) {
      for (const auto &entry : *object) {
        if (entry.first == key)
          return &entry.second;
      }
    }
    return nullptr;
  }

private:
  Storage data_;
};

// ---- Parser (recursive descent over a string_view) ----

inline void append_utf8(unsigned code, std::string &out) {
  if (code < 0x80) {
    out += static_cast<char>(code);
  } else if (code < 0x800) {
    out += static_cast<char>(0xC0 | (code >> 6));
    out += static_cast<char>(0x80 | (code & 0x3F));
  } else {
    out += static_cast<char>(0xE0 | (code >> 12));
    out += static_cast<char>(0x80 | ((code >> 6) & 0x3F));
    out += static_cast<char>(0x80 | (code & 0x3F));
  }
}

class Parser {
public:
  explicit Parser(std::string_view text) : text_(text) {}
  std::optional<Value> parse() {
    skip_ws();
    return parse_value();
  }

private:
  std::string_view text_;
  std::size_t pos_ = 0;

  void skip_ws() {
    while (pos_ < text_.size()) {
      const char c = text_[pos_];
      if (c == ' ' || c == '\t' || c == '\n' || c == '\r')
        ++pos_;
      else
        break;
    }
  }
  std::optional<Value> parse_value() {
    skip_ws();
    if (pos_ >= text_.size())
      return std::nullopt;
    switch (text_[pos_]) {
    case '{':
      return parse_object();
    case '[':
      return parse_array();
    case '"': {
      auto value = parse_string();
      if (!value)
        return std::nullopt;
      return Value(std::move(*value));
    }
    case 't':
    case 'f':
      return parse_bool();
    case 'n':
      return parse_null();
    default:
      return parse_number();
    }
  }
  std::optional<Value> parse_object() {
    Object object;
    ++pos_; // consume {
    skip_ws();
    if (pos_ < text_.size() && text_[pos_] == '}') {
      ++pos_;
      return Value(std::move(object));
    }
    while (pos_ < text_.size()) {
      skip_ws();
      auto key = parse_string();
      if (!key)
        return std::nullopt;
      skip_ws();
      if (pos_ >= text_.size() || text_[pos_] != ':')
        return std::nullopt;
      ++pos_;
      auto value = parse_value();
      if (!value)
        return std::nullopt;
      object.emplace_back(std::move(*key), std::move(*value));
      skip_ws();
      if (pos_ >= text_.size())
        return std::nullopt;
      if (text_[pos_] == ',') {
        ++pos_;
        continue;
      }
      if (text_[pos_] == '}') {
        ++pos_;
        return Value(std::move(object));
      }
      return std::nullopt;
    }
    return std::nullopt;
  }
  std::optional<Value> parse_array() {
    Array array;
    ++pos_; // consume [
    skip_ws();
    if (pos_ < text_.size() && text_[pos_] == ']') {
      ++pos_;
      return Value(std::move(array));
    }
    while (pos_ < text_.size()) {
      auto value = parse_value();
      if (!value)
        return std::nullopt;
      array.push_back(std::move(*value));
      skip_ws();
      if (pos_ >= text_.size())
        return std::nullopt;
      if (text_[pos_] == ',') {
        ++pos_;
        continue;
      }
      if (text_[pos_] == ']') {
        ++pos_;
        return Value(std::move(array));
      }
      return std::nullopt;
    }
    return std::nullopt;
  }
  std::optional<std::string> parse_string() {
    skip_ws();
    if (pos_ >= text_.size() || text_[pos_] != '"')
      return std::nullopt;
    ++pos_;
    std::string out;
    while (pos_ < text_.size()) {
      const char c = text_[pos_++];
      if (c == '"')
        return out;
      if (c == '\\') {
        if (pos_ >= text_.size())
          return std::nullopt;
        const char esc = text_[pos_++];
        switch (esc) {
        case '"':
          out += '"';
          break;
        case '\\':
          out += '\\';
          break;
        case '/':
          out += '/';
          break;
        case 'b':
          out += '\b';
          break;
        case 'f':
          out += '\f';
          break;
        case 'n':
          out += '\n';
          break;
        case 'r':
          out += '\r';
          break;
        case 't':
          out += '\t';
          break;
        case 'u': {
          if (pos_ + 4 > text_.size())
            return std::nullopt;
          unsigned code = 0;
          for (int i = 0; i < 4; ++i) {
            code <<= 4;
            const char h = text_[pos_++];
            if (h >= '0' && h <= '9')
              code |= static_cast<unsigned>(h - '0');
            else if (h >= 'a' && h <= 'f')
              code |= static_cast<unsigned>(h - 'a' + 10);
            else if (h >= 'A' && h <= 'F')
              code |= static_cast<unsigned>(h - 'A' + 10);
            else
              return std::nullopt;
          }
          append_utf8(code, out);
          break;
        }
        default:
          return std::nullopt;
        }
      } else {
        out += c;
      }
    }
    return std::nullopt;
  }
  std::optional<Value> parse_number() {
    const std::size_t start = pos_;
    bool is_double = false;
    if (pos_ < text_.size() && (text_[pos_] == '-' || text_[pos_] == '+'))
      ++pos_;
    while (pos_ < text_.size()) {
      const char c = text_[pos_];
      if (c >= '0' && c <= '9') {
        ++pos_;
      } else if (c == '.' || c == 'e' || c == 'E' || c == '+' || c == '-') {
        is_double = true;
        ++pos_;
      } else
        break;
    }
    if (pos_ == start)
      return std::nullopt;
    const std::string token(text_.substr(start, pos_ - start));
    try {
      if (is_double)
        return Value(std::stod(token));
      return Value(static_cast<std::int64_t>(std::stoll(token)));
    } catch (...) {
      return std::nullopt;
    }
  }
  std::optional<Value> parse_bool() {
    if (text_.compare(pos_, 4, "true") == 0) {
      pos_ += 4;
      return Value(true);
    }
    if (text_.compare(pos_, 5, "false") == 0) {
      pos_ += 5;
      return Value(false);
    }
    return std::nullopt;
  }
  std::optional<Value> parse_null() {
    if (text_.compare(pos_, 4, "null") == 0) {
      pos_ += 4;
      return Value(nullptr);
    }
    return std::nullopt;
  }
};

inline std::optional<Value> parse(std::string_view text) {
  Parser parser(text);
  return parser.parse();
}

// ---- Serializer ----

inline void dump_string(const std::string &value, std::string &out) {
  out += '"';
  for (const char ch : value) {
    switch (ch) {
    case '"':
      out += "\\\"";
      break;
    case '\\':
      out += "\\\\";
      break;
    case '\n':
      out += "\\n";
      break;
    case '\r':
      out += "\\r";
      break;
    case '\t':
      out += "\\t";
      break;
    case '\b':
      out += "\\b";
      break;
    case '\f':
      out += "\\f";
      break;
    default:
      if (static_cast<unsigned char>(ch) < 0x20) {
        char buffer[8];
        std::snprintf(buffer, sizeof(buffer), "\\u%04x", static_cast<unsigned char>(ch));
        out += buffer;
      } else {
        out += ch;
      }
    }
  }
  out += '"';
}

inline void dump_value(const Value &value, std::string &out) {
  std::visit(
      [&out](const auto &inner) {
        using T = std::decay_t<decltype(inner)>;
        if constexpr (std::is_same_v<T, std::nullptr_t>) {
          out += "null";
        } else if constexpr (std::is_same_v<T, bool>) {
          out += inner ? "true" : "false";
        } else if constexpr (std::is_same_v<T, std::int64_t>) {
          out += std::to_string(inner);
        } else if constexpr (std::is_same_v<T, double>) {
          char buffer[32];
          std::snprintf(buffer, sizeof(buffer), "%.17g", inner);
          out += buffer;
        } else if constexpr (std::is_same_v<T, std::string>) {
          dump_string(inner, out);
        } else if constexpr (std::is_same_v<T, Array>) {
          out += '[';
          bool first = true;
          for (const auto &element : inner) {
            if (!first)
              out += ',';
            first = false;
            dump_value(element, out);
          }
          out += ']';
        } else if constexpr (std::is_same_v<T, Object>) {
          out += '{';
          bool first = true;
          for (const auto &entry : inner) {
            if (!first)
              out += ',';
            first = false;
            dump_string(entry.first, out);
            out += ':';
            dump_value(entry.second, out);
          }
          out += '}';
        }
      },
      value.data());
}

inline std::string dump(const Value &value) {
  std::string out;
  dump_value(value, out);
  return out;
}

// ---- Generic encode/decode ----
//
// Forward declarations let the container overloads recurse through one another, and the
// generic fallbacks delegate models/enums to the per-type to_json/from_json found via ADL.
template <typename T> Value encode(const T &value);
template <typename T> Value encode(const std::optional<T> &value);
template <typename T> Value encode(const std::vector<T> &values);
template <typename T> Value encode(const std::map<std::string, T> &values);
template <typename... T> Value encode(const std::variant<T...> &value);
template <typename T> void decode(const Value &node, T &out);
template <typename T> void decode(const Value &node, std::optional<T> &out);
template <typename T> void decode(const Value &node, std::vector<T> &out);
template <typename T> void decode(const Value &node, std::map<std::string, T> &out);
template <typename... T> void decode(const Value &node, std::variant<T...> &out);

template <typename T> Value encode(const T &value) {
  if constexpr (std::is_same_v<T, bool>)
    return Value(value);
  else if constexpr (std::is_same_v<T, std::string>)
    return Value(value);
  else if constexpr (std::is_integral_v<T>)
    return Value(static_cast<std::int64_t>(value));
  else if constexpr (std::is_floating_point_v<T>)
    return Value(static_cast<double>(value));
  else
    return to_json(value); // models and enums: ADL-resolved per-type to_json
}
template <typename T> Value encode(const std::optional<T> &value) {
  if (!value.has_value())
    return Value(nullptr);
  return encode(*value);
}
template <typename T> Value encode(const std::vector<T> &values) {
  Array array;
  array.reserve(values.size());
  for (const auto &value : values)
    array.push_back(encode(value));
  return Value(std::move(array));
}
template <typename T> Value encode(const std::map<std::string, T> &values) {
  Object object;
  for (const auto &[key, value] : values)
    object.emplace_back(key, encode(value));
  return Value(std::move(object));
}
template <typename... T> Value encode(const std::variant<T...> &value) {
  return std::visit([](const auto &inner) { return encode(inner); }, value);
}

template <typename T> void decode(const Value &node, T &out) {
  if constexpr (std::is_same_v<T, bool>)
    out = node.as_bool();
  else if constexpr (std::is_same_v<T, std::string>)
    out = node.as_string();
  else if constexpr (std::is_integral_v<T>)
    out = static_cast<T>(node.as_int());
  else if constexpr (std::is_floating_point_v<T>)
    out = static_cast<T>(node.as_double());
  else
    from_json(node, out); // models and enums: ADL-resolved per-type from_json
}
template <typename T> void decode(const Value &node, std::optional<T> &out) {
  if (node.is_null()) {
    out.reset();
    return;
  }
  T value{};
  decode(node, value);
  out = std::move(value);
}
template <typename T> void decode(const Value &node, std::vector<T> &out) {
  out.clear();
  if (const Array *array = node.as_array()) {
    out.reserve(array->size());
    for (const auto &element : *array) {
      T value{};
      decode(element, value);
      out.push_back(std::move(value));
    }
  }
}
template <typename T> void decode(const Value &node, std::map<std::string, T> &out) {
  out.clear();
  if (const Object *object = node.as_object()) {
    for (const auto &entry : *object) {
      T value{};
      decode(entry.second, value);
      out.emplace(entry.first, std::move(value));
    }
  }
}
template <typename... T> void decode(const Value &, std::variant<T...> &) {
  // Unions are dispatched by a discriminator the response axis owns; leave the default variant.
}

} // namespace demo_api_scalar_galaxy::json
