// Code generated by Scalar SDK Generator. DO NOT EDIT.
#pragma once

#include <demo_api_scalar_galaxy_cpp/json.hpp>

#include <cstdint>
#include <map>
#include <optional>
#include <string>
#include <string_view>
#include <variant>
#include <vector>

namespace demo_api_scalar_galaxy {

// Every satellite in the Scalar Galaxy
struct Satellite {
  std::optional<std::int64_t> id;         // wire: "id"
  std::string name;                       // wire: "name"
  std::optional<std::string> description; // wire: "description"
  // Diameter in kilometers
  std::optional<double> diameter;                          // wire: "diameter"
  std::string type;                                        // wire: "type"
  std::optional<std::map<std::string, std::string>> orbit; // wire: "orbit"
};

inline json::Value to_json(const Satellite &value) {
  json::Object object;
  if (value.id.has_value())
    object.emplace_back("id", json::encode(*value.id));
  object.emplace_back("name", json::encode(value.name));
  if (value.description.has_value())
    object.emplace_back("description", json::encode(*value.description));
  if (value.diameter.has_value())
    object.emplace_back("diameter", json::encode(*value.diameter));
  object.emplace_back("type", json::encode(value.type));
  if (value.orbit.has_value())
    object.emplace_back("orbit", json::encode(*value.orbit));
  return json::Value(std::move(object));
}

inline void from_json(const json::Value &node, Satellite &value) {
  if (const json::Value *field = node.find("id"))
    json::decode(*field, value.id);
  if (const json::Value *field = node.find("name"))
    json::decode(*field, value.name);
  if (const json::Value *field = node.find("description"))
    json::decode(*field, value.description);
  if (const json::Value *field = node.find("diameter"))
    json::decode(*field, value.diameter);
  if (const json::Value *field = node.find("type"))
    json::decode(*field, value.type);
  if (const json::Value *field = node.find("orbit"))
    json::decode(*field, value.orbit);
}

// A user
struct User {
  std::optional<std::int64_t> id;  // wire: "id"
  std::optional<std::string> name; // wire: "name"
};

inline json::Value to_json(const User &value) {
  json::Object object;
  if (value.id.has_value())
    object.emplace_back("id", json::encode(*value.id));
  if (value.name.has_value())
    object.emplace_back("name", json::encode(*value.name));
  return json::Value(std::move(object));
}

inline void from_json(const json::Value &node, User &value) {
  if (const json::Value *field = node.find("id"))
    json::decode(*field, value.id);
  if (const json::Value *field = node.find("name"))
    json::decode(*field, value.name);
}

// A planet in the Scalar Galaxy
struct Planet {
  std::int64_t id;                        // wire: "id"
  std::string name;                       // wire: "name"
  std::optional<std::string> description; // wire: "description"
  std::string type;                       // wire: "type"
  // A score from 0 to 1 indicating potential habitability
  std::optional<double> habitability_index;                              // wire: "habitabilityIndex"
  std::optional<std::map<std::string, std::string>> physical_properties; // wire: "physicalProperties"
  // Atmospheric composition
  std::optional<std::vector<std::map<std::string, std::string>>> atmosphere; // wire: "atmosphere"
  std::optional<std::string> discovered_at;                                  // wire: "discoveredAt"
  std::optional<std::string> image;                                          // wire: "image"
  std::optional<std::vector<Satellite>> satellites;                          // wire: "satellites"
  // A user
  std::optional<User> creator;                  // wire: "creator"
  std::optional<std::vector<std::string>> tags; // wire: "tags"
  std::optional<std::string> last_updated;      // wire: "lastUpdated"
  // URL which gets invoked upon a successful operation
  std::optional<std::string> success_callback_url; // wire: "successCallbackUrl"
  // URL which gets invoked upon a failed operation
  std::optional<std::string> failure_callback_url; // wire: "failureCallbackUrl"
};

inline json::Value to_json(const Planet &value) {
  json::Object object;
  object.emplace_back("id", json::encode(value.id));
  object.emplace_back("name", json::encode(value.name));
  if (value.description.has_value())
    object.emplace_back("description", json::encode(*value.description));
  object.emplace_back("type", json::encode(value.type));
  if (value.habitability_index.has_value())
    object.emplace_back("habitabilityIndex", json::encode(*value.habitability_index));
  if (value.physical_properties.has_value())
    object.emplace_back("physicalProperties", json::encode(*value.physical_properties));
  if (value.atmosphere.has_value())
    object.emplace_back("atmosphere", json::encode(*value.atmosphere));
  if (value.discovered_at.has_value())
    object.emplace_back("discoveredAt", json::encode(*value.discovered_at));
  if (value.image.has_value())
    object.emplace_back("image", json::encode(*value.image));
  if (value.satellites.has_value())
    object.emplace_back("satellites", json::encode(*value.satellites));
  if (value.creator.has_value())
    object.emplace_back("creator", json::encode(*value.creator));
  if (value.tags.has_value())
    object.emplace_back("tags", json::encode(*value.tags));
  if (value.last_updated.has_value())
    object.emplace_back("lastUpdated", json::encode(*value.last_updated));
  if (value.success_callback_url.has_value())
    object.emplace_back("successCallbackUrl", json::encode(*value.success_callback_url));
  if (value.failure_callback_url.has_value())
    object.emplace_back("failureCallbackUrl", json::encode(*value.failure_callback_url));
  return json::Value(std::move(object));
}

inline void from_json(const json::Value &node, Planet &value) {
  if (const json::Value *field = node.find("id"))
    json::decode(*field, value.id);
  if (const json::Value *field = node.find("name"))
    json::decode(*field, value.name);
  if (const json::Value *field = node.find("description"))
    json::decode(*field, value.description);
  if (const json::Value *field = node.find("type"))
    json::decode(*field, value.type);
  if (const json::Value *field = node.find("habitabilityIndex"))
    json::decode(*field, value.habitability_index);
  if (const json::Value *field = node.find("physicalProperties"))
    json::decode(*field, value.physical_properties);
  if (const json::Value *field = node.find("atmosphere"))
    json::decode(*field, value.atmosphere);
  if (const json::Value *field = node.find("discoveredAt"))
    json::decode(*field, value.discovered_at);
  if (const json::Value *field = node.find("image"))
    json::decode(*field, value.image);
  if (const json::Value *field = node.find("satellites"))
    json::decode(*field, value.satellites);
  if (const json::Value *field = node.find("creator"))
    json::decode(*field, value.creator);
  if (const json::Value *field = node.find("tags"))
    json::decode(*field, value.tags);
  if (const json::Value *field = node.find("lastUpdated"))
    json::decode(*field, value.last_updated);
  if (const json::Value *field = node.find("successCallbackUrl"))
    json::decode(*field, value.success_callback_url);
  if (const json::Value *field = node.find("failureCallbackUrl"))
    json::decode(*field, value.failure_callback_url);
}

using CelestialBody = std::variant<Planet, Satellite>;

// Credentials to authenticate a user
struct Credentials {
  std::string email; // wire: "email"
};

inline json::Value to_json(const Credentials &value) {
  json::Object object;
  object.emplace_back("email", json::encode(value.email));
  return json::Value(std::move(object));
}

inline void from_json(const json::Value &node, Credentials &value) {
  if (const json::Value *field = node.find("email"))
    json::decode(*field, value.email);
}

// A paginated resource
struct PaginatedResource {
  std::optional<std::map<std::string, std::string>> meta; // wire: "meta"
};

inline json::Value to_json(const PaginatedResource &value) {
  json::Object object;
  if (value.meta.has_value())
    object.emplace_back("meta", json::encode(*value.meta));
  return json::Value(std::move(object));
}

inline void from_json(const json::Value &node, PaginatedResource &value) {
  if (const json::Value *field = node.find("meta"))
    json::decode(*field, value.meta);
}

// A token to authenticate a user
struct Token {
  std::optional<std::string> token; // wire: "token"
};

inline json::Value to_json(const Token &value) {
  json::Object object;
  if (value.token.has_value())
    object.emplace_back("token", json::encode(*value.token));
  return json::Value(std::move(object));
}

inline void from_json(const json::Value &node, Token &value) {
  if (const json::Value *field = node.find("token"))
    json::decode(*field, value.token);
}

} // namespace demo_api_scalar_galaxy
