// Code generated by Scalar SDK Generator. DO NOT EDIT.
#pragma once

#include <demo_api_scalar_galaxy_cpp/json.hpp>

#include <algorithm>
#include <chrono>
#include <cstdint>
#include <map>
#include <memory>
#include <optional>
#include <stdexcept>
#include <string>
#include <string_view>
#include <type_traits>
#include <utility>
#include <variant>
#include <vector>

namespace demo_api_scalar_galaxy {

struct RequestOptions {
  std::optional<std::string> base_url;
  std::map<std::string, std::string> headers;
  std::map<std::string, std::string> query;
  std::optional<std::chrono::milliseconds> timeout;
  std::optional<int> max_retries;
  bool raw_response = false;
};

struct Request {
  std::string method;
  std::string path_template;
  std::map<std::string, std::string> path_params;
  std::map<std::string, std::string> query;
  std::map<std::string, std::string> headers;
  std::map<std::string, std::string> cookies;
  std::optional<std::string> body;
  std::optional<std::string> content_type;
  bool streaming = false;
  std::optional<std::string> stream_format;
};

struct RawResponse {
  int status_code = 0;
  std::map<std::string, std::string> headers;
  std::string body;
};

template <typename T> struct Response {
  int status_code = 0;
  std::map<std::string, std::string> headers;
  std::string raw_body;
  T data{};
};

template <typename TData, typename TError> struct ResultResponse {
  std::optional<TData> data;
  std::optional<TError> error;
  int status_code = 0;
  std::map<std::string, std::string> headers;
  std::string raw_body;
};

template <typename T> struct Page {
  Response<T> response;
  std::string items_field;
  std::optional<std::string> next_cursor;
  std::optional<std::int64_t> next_offset;
  std::optional<std::int64_t> next_page;
};

template <typename T> struct StreamResponse {
  Response<T> response;
  std::string stream_format;
};

class Transport {
public:
  virtual ~Transport() = default;
  virtual RawResponse send(const Request &request, const RequestOptions &options) = 0;
};

class MissingTransportError : public std::runtime_error {
public:
  MissingTransportError() : std::runtime_error("No transport configured for generated C++ SDK client") {}
};

class APIConnectionError : public std::runtime_error {
public:
  explicit APIConnectionError(std::string message) : std::runtime_error(std::move(message)) {}
};

inline std::optional<std::chrono::system_clock::time_point> parse_http_date_retry_after(std::string_view retry_after) {
  (void)retry_after;
  return std::nullopt;
}

inline std::optional<std::chrono::milliseconds> retry_after_delay(const std::map<std::string, std::string> &headers) {
  auto retry_after = headers.find("Retry-After"); // retryAfterHeader honors Retry-After.
  if (retry_after == headers.end())
    retry_after = headers.find("retry-after");
  if (retry_after == headers.end())
    return std::nullopt;
  try {
    const double seconds = std::stod(retry_after->second);
    if (seconds >= 0)
      return std::chrono::milliseconds(static_cast<std::int64_t>(seconds * 1000));
  } catch (...) {
  }
  if (const auto date = parse_http_date_retry_after(retry_after->second)) {
    return std::chrono::duration_cast<std::chrono::milliseconds>(*date - std::chrono::system_clock::now());
  }
  return std::nullopt;
}

inline std::chrono::milliseconds retry_delay(int attempt, const std::map<std::string, std::string> &headers) {
  if (const auto retry_after = retry_after_delay(headers))
    return *retry_after;
  const int capped = std::min(8000, 1000 * (1 << std::min(attempt, 3)));
  return std::chrono::milliseconds(capped);
}

inline std::string to_request_value(const std::string &value) { return value; }
inline std::string to_request_value(std::string_view value) { return std::string(value); }
inline std::string to_request_value(const char *value) { return std::string(value); }
inline std::string to_request_value(bool value) { return value ? "true" : "false"; }
template <typename T> std::string to_request_value(const T &value) {
  if constexpr (requires { wire_value(value); }) {
    return std::string(wire_value(value));
  } else if constexpr (std::is_arithmetic_v<T>) {
    return std::to_string(value);
  } else {
    return {};
  }
}

template <typename T> std::string to_request_value(const std::vector<T> &values) {
  std::string out;
  for (const auto &value : values) {
    if (!out.empty())
      out += ",";
    out += to_request_value(value);
  }
  return out;
}

template <typename T> std::string to_request_value(const std::map<std::string, T> &) { return "{}"; }

template <typename... T> std::string to_request_value(const std::variant<T...> &value) {
  return std::visit([](const auto &item) { return to_request_value(item); }, value);
}

template <typename T> std::optional<std::string> to_optional_request_value(const std::optional<T> &value) {
  if (!value.has_value())
    return std::nullopt;
  return to_request_value(*value);
}

// Serializes a request model to a JSON body via the generated per-model to_json (ADL).
template <typename T> std::string to_request_body(const T &value) { return json::dump(json::encode(value)); }

} // namespace demo_api_scalar_galaxy
