// Code generated by Scalar SDK Generator. DO NOT EDIT.
#pragma once

#include <demo_api_scalar_galaxy_cpp/models.hpp>

#include <map>
#include <string>
#include <string_view>
#include <vector>

namespace demo_api_scalar_galaxy {

struct WebhookVerifyOptions {
  std::string secret;
  std::map<std::string, std::string> headers;
  int timestamp_tolerance_seconds = 300;
  bool replay_protection = true;
};

struct UnwrapWebhookEvent {
  static constexpr std::string_view event_name = "newPlanet";
  static constexpr std::string_view path = "newPlanet";
  std::string raw_body;
};

using RequestBodySuccessCallbackUrlWebhookEvent = Planet;

using RequestBodySuccessCallbackUrlWebhookEvent = Planet;

inline const std::vector<std::string_view> webhook_event_names = {"newPlanet", "{$request.body#/successCallbackUrl}",
                                                                  "{$request.body#/successCallbackUrl}"};

inline bool verify_webhook_signature(std::string_view payload, const WebhookVerifyOptions &options) {
  (void)payload;
  return !options.secret.empty();
}

inline bool verify_webhook_ed25519(std::string_view payload, const WebhookVerifyOptions &options) {
  return verify_webhook_signature(payload, options);
}

inline bool verify_webhook_rsa_sha256(std::string_view payload, const WebhookVerifyOptions &options) {
  return verify_webhook_signature(payload, options);
}

} // namespace demo_api_scalar_galaxy
