// Code generated by Scalar SDK Generator. DO NOT EDIT.
#include <demo_api_scalar_galaxy_cpp/client.hpp>

#include <cstdlib>
#include <stdexcept>
#include <utility>

namespace demo_api_scalar_galaxy {

namespace {

std::optional<std::string> first_present(std::optional<std::string> configured, const char *env_name) {
  if (configured.has_value() && !configured->empty())
    return configured;
  if (const char *env_value = std::getenv(env_name))
    return std::string(env_value);
  return std::nullopt;
}

} // namespace

ApiClient::ApiClient(ClientOptions options) : options_(std::move(options)) {
  bearer_auth_token_ = first_present(options_.bearer_auth_token, "BEARER_AUTH_TOKEN");
  basic_auth_credentials_ = first_present(options_.basic_auth_credentials, "BASIC_AUTH_TOKEN");
  x_api_key_ = first_present(options_.x_api_key, "API_KEY_HEADER_X_API_KEY");
  api_key_ = first_present(options_.api_key, "API_KEY_QUERY_API_KEY");
  api_key_ = first_present(options_.api_key, "API_KEY_COOKIE_API_KEY");
  o_auth2_access_token_ = first_present(options_.o_auth2_access_token, "O_AUTH2_TOKEN");
  open_id_connect_access_token_ = first_present(options_.open_id_connect_access_token, "OPEN_ID_CONNECT_TOKEN");
}

RawResponse ApiClient::send_raw(Request request, const RequestOptions &request_options) const {
  if (!options_.transport)
    throw MissingTransportError();
  for (const auto &[key, value] : options_.default_headers)
    request.headers.try_emplace(key, value);
  for (const auto &[key, value] : options_.default_query)
    request.query.try_emplace(key, value);
  const int max_retries = request_options.max_retries.value_or(options_.max_retries);
  RawResponse response;
  for (int attempt = 0; attempt <= max_retries; ++attempt) {
    response = options_.transport->send(request, request_options);
    const bool retryable = response.status_code == 429 || response.status_code >= 500;
    if (!retryable || attempt == max_retries)
      break;
    const auto delay = retry_delay(attempt, response.headers);
    (void)delay;
  }
  return response;
}

void ApiClient::apply_auth(Request &request) const {
  if (bearer_auth_token_)
    request.headers.try_emplace("Authorization", "Bearer " + *bearer_auth_token_);
  if (basic_auth_credentials_)
    request.headers.try_emplace("Authorization", "Basic " + *basic_auth_credentials_);
  if (x_api_key_)
    request.headers.try_emplace("X-API-Key", *x_api_key_);
  if (api_key_)
    request.query.try_emplace("api_key", *api_key_);
  if (api_key_)
    request.cookies.try_emplace("api_key", *api_key_);
  if (o_auth2_access_token_)
    request.headers.try_emplace("Authorization", "Bearer " + *o_auth2_access_token_);
  if (open_id_connect_access_token_)
    request.headers.try_emplace("Authorization", "Bearer " + *open_id_connect_access_token_);
}

DemoApiScalarGalaxyClient::DemoApiScalarGalaxyClient(ClientOptions options)
    : api_(std::move(options)), planets(api_), celestial_bodies(api_), authentication(api_) {}

} // namespace demo_api_scalar_galaxy
