// Code generated by Scalar SDK Generator. DO NOT EDIT.
#pragma once

#include <demo_api_scalar_galaxy_cpp/models.hpp>
#include <demo_api_scalar_galaxy_cpp/request.hpp>

namespace demo_api_scalar_galaxy {

class ApiClient;

class AuthenticationResource {
public:
  explicit AuthenticationResource(ApiClient &client);

  struct CreateUserResultMetadata {
    using ResponseType = User;
    using RawResponseType = Response<RawResponse>;
    static constexpr std::string_view method = "POST";
    static constexpr std::string_view path = "/user/signup";
    static constexpr std::string_view result = "Response<User>";
    static constexpr std::string_view response_model = "user";
    static constexpr std::string_view error_responses = "400:,401:,403:,409:,422:";
  };

  struct CreateUserParams {
    std::string content_type = "application/json"; // content type selector
    std::optional<std::string> name;               // body: "name"
    std::string email;                             // body: "email"
    std::string password;                          // body: "password"
  };

  Response<User> create_user(const CreateUserParams &params, const RequestOptions &request_options = {}) const;
  Response<RawResponse> create_user_raw(const CreateUserParams &params,
                                        const RequestOptions &request_options = {}) const;

  struct CreateTokenResultMetadata {
    using ResponseType = Token;
    using RawResponseType = Response<RawResponse>;
    static constexpr std::string_view method = "POST";
    static constexpr std::string_view path = "/auth/token";
    static constexpr std::string_view result = "Response<Token>";
    static constexpr std::string_view response_model = "token";
    static constexpr std::string_view error_responses = "400:,401:,403:";
  };

  struct CreateTokenParams {
    std::string content_type = "application/json"; // content type selector
    std::string email;                             // body: "email"
    std::string password;                          // body: "password"
  };

  Response<Token> create_token(const CreateTokenParams &params, const RequestOptions &request_options = {}) const;
  Response<RawResponse> create_token_raw(const CreateTokenParams &params,
                                         const RequestOptions &request_options = {}) const;

  struct ListMeResultMetadata {
    using ResponseType = User;
    using RawResponseType = Response<RawResponse>;
    static constexpr std::string_view method = "GET";
    static constexpr std::string_view path = "/me";
    static constexpr std::string_view result = "Response<User>";
    static constexpr std::string_view response_model = "user";
    static constexpr std::string_view error_responses = "401:,403:";
  };

  Response<User> list_me(const RequestOptions &request_options = {}) const;
  Response<RawResponse> list_me_raw(const RequestOptions &request_options = {}) const;

private:
  ApiClient &client_;
};

} // namespace demo_api_scalar_galaxy
