// Code generated by Scalar SDK Generator. DO NOT EDIT.
#pragma once

#include <demo_api_scalar_galaxy_cpp/models.hpp>
#include <demo_api_scalar_galaxy_cpp/request.hpp>

namespace demo_api_scalar_galaxy {

class ApiClient;

class CelestialBodiesResource {
public:
  explicit CelestialBodiesResource(ApiClient &client);

  struct CreateResultMetadata {
    using ResponseType = CelestialBody;
    using RawResponseType = Response<RawResponse>;
    static constexpr std::string_view method = "POST";
    static constexpr std::string_view path = "/celestial-bodies";
    static constexpr std::string_view result = "Response<CelestialBody>";
    static constexpr std::string_view response_model = "celestial_body";
    static constexpr std::string_view error_responses = "";
  };

  struct CreateParams {
    CelestialBody body; // body
  };

  Response<CelestialBody> create(const CreateParams &params, const RequestOptions &request_options = {}) const;
  Response<RawResponse> create_raw(const CreateParams &params, const RequestOptions &request_options = {}) const;

private:
  ApiClient &client_;
};

} // namespace demo_api_scalar_galaxy
