// Code generated by Scalar SDK Generator. DO NOT EDIT.
#pragma once

#include <demo_api_scalar_galaxy_cpp/models.hpp>
#include <demo_api_scalar_galaxy_cpp/request.hpp>

namespace demo_api_scalar_galaxy {

class ApiClient;

class PlanetsResource {
public:
  explicit PlanetsResource(ApiClient &client);

  struct ListResultMetadata {
    using ResponseType = std::map<std::string, std::string>;
    using RawResponseType = Response<RawResponse>;
    static constexpr std::string_view method = "GET";
    static constexpr std::string_view path = "/planets";
    static constexpr std::string_view result = "Response<std::map<std::string, std::string>>";
    static constexpr std::string_view response_model = "";
    static constexpr std::string_view error_responses = "";
  };

  struct ListParams {
    std::optional<std::int64_t> limit;  // query: "limit"
    std::optional<std::int64_t> offset; // query: "offset"
  };

  Response<std::map<std::string, std::string>> list(const ListParams &params,
                                                    const RequestOptions &request_options = {}) const;
  Response<RawResponse> list_raw(const ListParams &params, const RequestOptions &request_options = {}) const;

  struct CreateResultMetadata {
    using ResponseType = Planet;
    using RawResponseType = Response<RawResponse>;
    static constexpr std::string_view method = "POST";
    static constexpr std::string_view path = "/planets";
    static constexpr std::string_view result = "Response<Planet>";
    static constexpr std::string_view response_model = "planet";
    static constexpr std::string_view error_responses = "400:,403:";
  };

  struct CreateParams {
    std::string content_type = "application/json";                             // content type selector
    std::string name;                                                          // body: "name"
    std::optional<std::string> description;                                    // body: "description"
    std::string type;                                                          // body: "type"
    std::optional<double> habitability_index;                                  // body: "habitabilityIndex"
    std::optional<std::map<std::string, std::string>> physical_properties;     // body: "physicalProperties"
    std::optional<std::vector<std::map<std::string, std::string>>> atmosphere; // body: "atmosphere"
    std::optional<std::string> discovered_at;                                  // body: "discoveredAt"
    std::optional<std::string> image;                                          // body: "image"
    std::optional<std::vector<Satellite>> satellites;                          // body: "satellites"
    std::optional<User> creator;                                               // body: "creator"
    std::optional<std::vector<std::string>> tags;                              // body: "tags"
    std::optional<std::string> success_callback_url;                           // body: "successCallbackUrl"
    std::optional<std::string> failure_callback_url;                           // body: "failureCallbackUrl"
  };

  Response<Planet> create(const CreateParams &params, const RequestOptions &request_options = {}) const;
  Response<RawResponse> create_raw(const CreateParams &params, const RequestOptions &request_options = {}) const;

  struct RetrieveResultMetadata {
    using ResponseType = Planet;
    using RawResponseType = Response<RawResponse>;
    static constexpr std::string_view method = "GET";
    static constexpr std::string_view path = "/planets/{planetId}";
    static constexpr std::string_view result = "Response<Planet>";
    static constexpr std::string_view response_model = "planet";
    static constexpr std::string_view error_responses = "404:";
  };

  struct RetrieveParams {
    std::int64_t planet_id; // path: "planetId"
  };

  Response<Planet> retrieve(const RetrieveParams &params, const RequestOptions &request_options = {}) const;
  Response<RawResponse> retrieve_raw(const RetrieveParams &params, const RequestOptions &request_options = {}) const;

  struct UpdateResultMetadata {
    using ResponseType = Planet;
    using RawResponseType = Response<RawResponse>;
    static constexpr std::string_view method = "PUT";
    static constexpr std::string_view path = "/planets/{planetId}";
    static constexpr std::string_view result = "Response<Planet>";
    static constexpr std::string_view response_model = "planet";
    static constexpr std::string_view error_responses = "400:,403:,404:";
  };

  struct UpdateParams {
    std::string content_type = "application/json";                             // content type selector
    std::int64_t planet_id;                                                    // path: "planetId"
    std::string name;                                                          // body: "name"
    std::optional<std::string> description;                                    // body: "description"
    std::string type;                                                          // body: "type"
    std::optional<double> habitability_index;                                  // body: "habitabilityIndex"
    std::optional<std::map<std::string, std::string>> physical_properties;     // body: "physicalProperties"
    std::optional<std::vector<std::map<std::string, std::string>>> atmosphere; // body: "atmosphere"
    std::optional<std::string> discovered_at;                                  // body: "discoveredAt"
    std::optional<std::string> image;                                          // body: "image"
    std::optional<std::vector<Satellite>> satellites;                          // body: "satellites"
    std::optional<User> creator;                                               // body: "creator"
    std::optional<std::vector<std::string>> tags;                              // body: "tags"
    std::optional<std::string> success_callback_url;                           // body: "successCallbackUrl"
    std::optional<std::string> failure_callback_url;                           // body: "failureCallbackUrl"
  };

  Response<Planet> update(const UpdateParams &params, const RequestOptions &request_options = {}) const;
  Response<RawResponse> update_raw(const UpdateParams &params, const RequestOptions &request_options = {}) const;

  struct DeleteResultMetadata {
    using ResponseType = std::string;
    using RawResponseType = Response<RawResponse>;
    static constexpr std::string_view method = "DELETE";
    static constexpr std::string_view path = "/planets/{planetId}";
    static constexpr std::string_view result = "Response<std::string>";
    static constexpr std::string_view response_model = "";
    static constexpr std::string_view error_responses = "404:";
  };

  struct DeleteParams {
    std::int64_t planet_id; // path: "planetId"
  };

  Response<std::string> delete_(const DeleteParams &params, const RequestOptions &request_options = {}) const;
  Response<RawResponse> delete__raw(const DeleteParams &params, const RequestOptions &request_options = {}) const;

  struct UploadImageResultMetadata {
    using ResponseType = std::map<std::string, std::string>;
    using RawResponseType = Response<RawResponse>;
    static constexpr std::string_view method = "POST";
    static constexpr std::string_view path = "/planets/{planetId}/image";
    static constexpr std::string_view result = "Response<std::map<std::string, std::string>>";
    static constexpr std::string_view response_model = "";
    static constexpr std::string_view error_responses = "400:,403:,404:";
  };

  struct UploadImageParams {
    std::int64_t planet_id;           // path: "planetId"
    std::optional<std::string> image; // body: "image"
  };

  Response<std::map<std::string, std::string>> upload_image(const UploadImageParams &params,
                                                            const RequestOptions &request_options = {}) const;
  Response<RawResponse> upload_image_raw(const UploadImageParams &params,
                                         const RequestOptions &request_options = {}) const;

private:
  ApiClient &client_;
};

} // namespace demo_api_scalar_galaxy
